config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  
  #notify_to :users
  get 'welcome/index'
  #root to: 'welcome#index'
  root to: 'posts#index'
  #root to: 'notifications#index'
  
  #post "omniauth_callbacks" => "/auth/omniauth_callbacks"
  #post "/auth/facebook/callback" => "/accounts/auth/facebook/callback"

  	resources :posts do
  		resources :comments
  		resources :likes
  	end

  	resources :users, only: [:show] do
  		member do
  			get :following, :followers
  			post :follow, :unfollow

  		end
  	end

    resources :posts do
      member do     
        put "like" => "posts#like"
        put "notifications" => "notifications#index"
      end
    end

    resources :charges, only: [:new, :create]
    get 'charges/new'
    get 'charges/create'

    resources :notifications, only: [:index]
    get 'notifications/index'

    resources :suggestions, only: [:index]
    get 'suggestions/index'

    
    resources :orders
    #get 'orders/create_order'
    #get 'orders/capture_order'
    post "create_order" => "orders#create_order"
    post "capture_order" => "orders#capture_order"

    resources :users do
      collection do
        post 'import'
      end
    end
    # post 'import_users' => 'users#import_users', as: 'import_users'
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :likes, dependent: :destroy
	has_rich_text :text
	has_many :comments, dependent: :destroy
	belongs_to :user

	acts_as_votable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#after_action { notify }
	before_action :authenticate_user!
	respond_to :js, :html, :json

	def new
		@post = Post.new
	end
	
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@posts = current_user.posts
	 	
	 	if @post.save
		 	redirect_to @post
	 	else
	 		render 'new'
	 	end

	 	respond_to do |format|
	 		format.html
	 		format.js { render 'posts/create.js.erb'}
	 	end
	end

	def index
		@post = Post.new
	 	@posts = Post.all
	 	@users = User.all
	end
		
	def show
	 	@post = Post.find(params[:id])
	end
		
	def edit
		@post = Post.find(params[:id])
	end
		
	def update
		@post = Post.find(params[:id])
		
		if @post.update(post_params)
 	    	redirect_to @post
	 	else
	 	    render 'edit'
	 	end
	end

	def like

		@post = Post.find(params[:id])

		if params[:value] == 'like'
			@post.liked_by current_user
		elsif params[:value] == 'unlike'
	      	@post.unliked_by current_user
	    end

	    respond_to do |format|
	    	format.html #{render 'posts/show.html.erb'}
	    	format.js { render 'posts/show.js.erb'}
	    end
	end
		
	def destroy
	 	@post = Post.find(params[:id])
	 	@post.destroy
		redirect_to posts_path
	end


	

	private
		def post_params
	    	params.require(:post).permit(:text)
	   	end
	   	
	 	def notify
	   		Notification.create(event: "New Notification")
	   	end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>

 <p>
   <%= form.label :text %><br>
   <%= form.rich_text_area :text %>
 </p>

 <p>
 	<%= form.submit %>
 </p> 

 <% end %>

app/views/posts/_like.html.erb
<p> Dynamic like </p>
<span class="parent-likes" >
  

  <div>

    <% if current_user.liked? @post %>
    
      <div> 
        <%= link_to like_post_path(@post, value: 'unlike'),  class: "unlike-btn", method: :put, remote: true do %>Unlike <span class="like_count" <%= @post.id %> >
        <%= @post.get_likes.count %> &#128591 </span> </div>
      <% end %>
    
    <% else %>
    
      <div> <%= link_to like_post_path(@post, value: 'like'), class: "like-btn", method: :put, remote: true do %>Like  <span class="like_count" <%= @post.id %> >
      <%= @post.get_likes.count %> &#128591 </span> </div>
      <% end %>
    
    <% end %>
  </div>
</span>

app/views/posts/create.js.erb
$("#post_like<%= @post.id%>").html("<%= escape_javascript(render partial: 'posts/show', locals: {post: @post}) %>");
// $(".post").text("<%= @post.likes.count %><%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%>");
$("#post_like<%= @post.id%> .post").text('<%= @post.likes.count%>');

app/views/posts/edit.html.erb
<p> Edit post</p>
<%= form_with(model: @post, local: true) do |form| %>

	<p>
		<%= form.label :text %>
		<%= form.rich_text_area :text %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div>
  <% if @current_user == @user %>   

  <h5><%= "Welcome #{current_user.user_name} !" %></h5>
  
  <% elsif current_user.followees.include?(@user) %>   
  
    <h5><%= button_to "UnFollow #{@user.user_name}",     
         unfollow_user_path, method: "POST" %></h5>
    
    <% else %>   

    <h5><%= button_to "Follow #{@user.user_name}", follow_user_path, 
         method: "POST"  %></h5>
  <% end %>

</div>

<div class="column left" style="background-color:#ffefef73;">
  <h2>menu</h2>
  <p>Some options</p>
  <a href="/notifications/index"> Notification <i class="fa fa-bell" aria-hidden="true"></i> </a>

  <a href="/suggestions/index"> Suggestions</a> <br>

  <a href="/charges/new"> Stripe </a> <br>

  <%= link_to "Paypal", orders_path %>

</div>





<div class="column middle" style="background-color:#fff;">
  <div class="text-editor-col">
    <%= render 'posts/form' %>
  </div>

  <div class="post" >
    <% @posts.each do |post| %>
    <div class="post-mid" >
      <a href=""> <i class="fa fa-user-circle" aria-hidden="true"></i>
      <% p = post.user_id %> 
      <%= link_to post.user.user_name, user_path(p) %>  </a>
      <strong> <%= post.text %><br> </strong> 
      <%= post.cached_votes_total %> <%= (post.cached_votes_total) == 1 ? 'Like' : 'Likes'%>

      <% if current_user == post.user %>

      <%= link_to 'Show', post_path(post) %>

      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post_path(post),method: :delete,data: { confirm: 'Are you sure?' } %>
      

      <% else %>

      <%= link_to 'Show', post_path(post) %>

      <% end %>

    </div>
    <% end %>

  </div>

  <%= flash[:notice] %>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>DOB</th>
      </tr>
    </thead>

    <% @users.each do |user| %>
    <tr>
      <td> <%= user.user_name %> </td>
      <td> <%= user.email %> </td>
      <th> <%= user.phone %> </th>
      <th> <%= user.dob %> </th>
    </tr>
    <% end %>
  </table>

  <div>        
    <h4> Import Users Using CSV! </h4>
    <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV"  %>
    <p>    </p>
    <% end %>
  </div>

</div>







<div class="column right" style="background-color:#ffefef73;">
  
  <% if user_signed_in? %>
  
  <p> User_id: <%= current_user.id %> </p>

  <a href=""> <i class="fa fa-user-circle" aria-hidden="true"></i>  
    <% q = current_user.id %> 
    <%= link_to current_user.user_name, user_path(q) %>
  </a><br>


  <a href="#"><%=  link_to 'logout',destroy_user_session_path,method: :delete %></a><br>

  <table class="a" width="200">
    <thead>
      <tr style="color: red" >
        <th scope="col"  > <%= current_user.posts.count %> </th>
        <th scope="col"  > <%= current_user.followers.count %> </th>
        <th scope="col"  > <%= current_user.followees.count %> </th>
      </tr>
    </thead>
    <tbody>
      <tr class="row2" >
        <td><%= (@posts.count) == 1 ? 'Post' : 'Posts'%></td>
        <td> Followers </td>
        <td> Following </td>
      </tr>
    </tbody>
  </table>

    
  <% else %>
      
  <a href="/users/sign_in"> <i class="fa fa-sign-in" aria-hidden="true"></i> <%=  link_to 'login', user_session_path %></a><br>
      
  <a href="#"><%= link_to 'signup', new_user_registration_path %></a><br>

  <% end %>

  

</div>

app/views/posts/new.html.erb
<h1>new post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div>
  <strong>Post:</strong>
  <%= @post.text %>

</div>


<p><%#= @post.likes.count %> <%#= (@post.likes.count) == 1 ? 'Like' : 'Likes'%> </p>

<%# pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<%# if pre_like %>
  <%#= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete, remote: true %>
<%# else %>
  <%#= button_to 'Like', post_likes_path(@post), method: :post, remote: true %>

<%#end %>

<div class="share-icons">
  <%= render "layouts/share/twitter"%>
</div>


<div class="post_like" > 
  <%= render 'posts/like' %>
</div>




<% @post.comments.each do |comment| %>

  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>


<h2>Add a comment:</h2>
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.rich_text_area :body %>
  </p>

  <p> 
    <%= form.hidden_field :post_id, :value => @post.id %>
    <%= form.hidden_field :user_id, :value => current_user.id %>

  </p>

  <p>
  	<%= form.submit %>
  </p>

  

  <% end %>

  <%= link_to 'Back', posts_path %>

app/views/posts/show.js.erb
<% if current_user.liked? @post %>
	$('.like-btn').removeClass('liked');
<% else %>
	$('.like-btn').addClass('like-btn');
<% end %>
$('.like_count').html("<%= @post.get_upvotes.size %>")


// $('.unlike-btn').on('ajax:success', function(){
//   $(this).parent().parent().find('.like_count')
//   .html('<% @post.get_likes.count %> &#128591');
//   $(this).closest('.unlike-btn').html('Like');
// });

// $('.like-btn').on('ajax:success', function(){
//   $(this).parent().parent().find('.like_count')
//   .html('<% @post.get_likes.count %> &#128591');
//   $(this).closest('.like-btn').html('Unlike');
// });